<?php

namespace App\Support;

final class LinkError
{
    public const LINK_NOT_FOUND = 'LINK_NOT_FOUND';

    public const LINK_DISABLED = 'LINK_DISABLED';

    public const USER_DISABLED = 'USER_DISABLED';

    public const MEMBERSHIP_EXPIRED = 'MEMBERSHIP_EXPIRED';

    public const QUOTA_EXCEEDED = 'QUOTA_EXCEEDED';

    public const MINI_PROGRAM_FORBIDDEN = 'MINI_PROGRAM_FORBIDDEN';

    public const SHARE_ORIGIN_UNAVAILABLE = 'SHARE_ORIGIN_UNAVAILABLE';

    public const LINK_TYPE_FORBIDDEN = 'LINK_TYPE_FORBIDDEN';

    public const LINK_TYPE_UNSUPPORTED = 'LINK_TYPE_UNSUPPORTED';

    public const VISITOR_TOKEN_INVALID = 'VISITOR_TOKEN_INVALID';

    public const QR_UNAVAILABLE = 'QR_UNAVAILABLE';

    public const UNSAFE_URL = 'UNSAFE_URL';

    public const MINI_PROGRAM_EXTERNAL_ERROR = 'MINI_PROGRAM_EXTERNAL_ERROR';

    public const KING_DOC_EXTERNAL_ERROR = 'KING_DOC_EXTERNAL_ERROR';

    public const CLI_QR_EXTERNAL_ERROR = 'CLI_QR_EXTERNAL_ERROR';

    public const WORK_WECHAT_EXTERNAL_ERROR = 'WORK_WECHAT_EXTERNAL_ERROR';

    public const LANDING_MINI_EXTERNAL_ERROR = 'LANDING_MINI_EXTERNAL_ERROR';

    public const QQ_QR_EXTERNAL_ERROR = 'QQ_QR_EXTERNAL_ERROR';
}
